// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";
import path from "path";
import { fileURLToPath } from "url";

// Manually point to your global .env if it's in the root
const __dirname = path.dirname(fileURLToPath(import.meta.url));
import dotenv from "dotenv";
dotenv.config({ path: path.resolve(__dirname, "../.env") }); 

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // We use a fallback check to ensure the CLI sees a string
    url: process.env["DATABASE_URL"] || "",
  },
});